---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup 
  namespace: splunk
  labels:
    app: splunk
    role: splunk_backup
    tier: backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splunk
      role: splunk_backup
  template:
    metadata:
      labels:
        app: splunk
        role: splunk_backup
        tier: backup
    spec:
      hostname: backup
      dnsPolicy: ClusterFirst
      dnsConfig:
        searches:
          - indexer.splunk.svc.cluster.local
      containers:
        - name: backup 
          image: sebastus/splunk-aks-backup-func:v0.0.5
          env:
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: splunk-backup-admin
                  key: azure_tenant_id            
            - name: AZURE_APP_ID
              valueFrom:
                secretKeyRef:
                  name: splunk-backup-admin
                  key: azure_app_id            
            - name: AZURE_APP_KEY
              valueFrom:
                secretKeyRef:
                  name: splunk-backup-admin
                  key: azure_app_key            
            - name: AZURE_SUBSCRIPTION_ID
              valueFrom:
                secretKeyRef:
                  name: splunk-backup-admin
                  key: azure_subscription_id            
            - name: AKS_RG
              valueFrom:
                secretKeyRef:
                  name: splunk-backup-admin
                  key: aks_rg            
            - name: AKS_ASSET_RG
              valueFrom:
                secretKeyRef:
                  name: splunk-backup-admin
                  key: aks_asset_rg            
            - name: AKS_NAME
              valueFrom:
                secretKeyRef:
                  name: splunk-backup-admin
                  key: aks_name            

