apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: proxy
  namespace: splunk
  labels:
    app: splunk
    role: splunk_proxy
    tier: proxy
spec:
  replicas: {{ .Values.proxy.replicaCount | default 3 }}
  selector:
    matchLabels:
      app: splunk
      role: splunk_proxy
  serviceName: proxy
  template:
    metadata:
      labels:
        app: splunk
        role: splunk_proxy
        tier: proxy
    spec:
      dnsPolicy: ClusterFirst
      dnsConfig:
        searches:
          - proxy.{{ .Values.general.namespace | default "splunk" }}.svc.cluster.local
      containers:
        - name: indexer
          image: sebastus/splunkproxyfunction:v1.0.0
          env:
            - name: AzureWebJobsStorage
              value: DefaultEndpointsProtocol=https;AccountName=gregfunctionproxy;AccountKey=8L3VtWk8XCFhVISM31T/Ys0yAxMHjrItf8QJobeM7TuzGSm/OGtIPvaMhr9QWKZMfVpu7Mq6Ko9V1cu5TIvJeA==
            - name: input-hub-name
              value: output-to-proxy
            - name: hubConnection
              value: Endpoint=sb://asdt-benchmark-eventhub-q81wx1pkcc.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=UGN8aCkwjpD0/E0kW56KoSI2szs8znGE9BA7u99jfRc= 
            - name: splunkAddress
              value: https://indexer-lb.splunk.svc.cluster.local:8088/services/collector
            - name: splunkToken
              value: c5f2415d-ca48-44d6-9f28-40c4cbe91bb5
            - name: splunkCertThumbprint
              value: 39e41d46954c315f2fc56f7e62229a7e7422ab44 
