apiVersion: apps/v1
kind: Deployment
metadata:
  name: search 
  namespace: splunk
  labels:
    app: splunk
    role: splunk_search_head
    tier: search
spec:
  replicas: {{ .Values.search.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: splunk
      role: splunk_search_head
  template:
    metadata:
      labels:
        app: splunk
        role: splunk_search_head
        tier: search
    spec:
      hostname: search
      dnsPolicy: ClusterFirst
      dnsConfig:
        searches:
          - indexer.{{ .Values.general.namespace | default "splunk" }}.svc.cluster.local
      containers:
        - name: search
          image: splunk/splunk:latest
          env:
            - name: SPLUNK_HOME
              value: /opt/splunk
            - name: SPLUNK_DEFAULTS_URL
              value: http://splunk-defaults/default.yml
            - name: SPLUNK_ROLE
              value: splunk_search_head
            - name: SPLUNK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: splunk-admin
                  key: password
            - name: SPLUNK_START_ARGS
              value: "--accept-license"
            - name: SPLUNK_CLUSTER_MASTER_URL
              value: master
            - name: SPLUNK_INDEXER_URL
              value: indexer-0,indexer-1,indexer-2
            - name: SPLUNK_SEARCH_HEAD_URL
              value: search
            - name: DEBUG
              value: "true"
          ports:
            - name: web
              containerPort: 8000
            - name: mgmt
              containerPort: 8089
            - name: kv
              containerPort: 8191
          volumeMounts:
            - name: splunk-search-data
              mountPath: /opt/splunk/var
            - name: splunk-search-config
              mountPath: /opt/splunk/etc
      volumes:
        - name: splunk-search-config
          persistentVolumeClaim:
            claimName: splunk-search-config
        - name: splunk-search-data
          persistentVolumeClaim:
            claimName: splunk-search-data
