apiVersion: v1
kind: Service
metadata:
  name: indexer-lb
  namespace: splunk
  labels:
    app: splunk
    role: splunk_indexer
    tier: indexer 
spec:
  type: LoadBalancer
  selector:
    app: splunk
    role: splunk_indexer
    tier: indexer
  ports:
    - name: hec
      port: 8088 
      targetPort: 8088
