---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy 
  namespace: splunk
  labels:
    app: splunk
    role: splunk_proxy
    tier: proxy
spec:
  replicas: {{ .Values.proxy.replicaCount | default 3 }}
  selector:
    matchLabels:
      app: splunk
      role: splunk_proxy
  template:
    metadata:
      labels:
        app: splunk
        role: splunk_proxy
        tier: proxy
    spec:
      hostname: proxy
      dnsPolicy: ClusterFirst
      dnsConfig:
        searches:
          - proxy.{{ .Values.general.namespace | default "splunk" }}.svc.cluster.local
      containers:
        - name: proxy 
          image: sebastus/splunkproxyfunction:v1.0.3 
          env:
            - name: AzureWebJobsStorage
              value: {{ .Values.proxy.AzureWebJobsStorage }}
            - name: hubConnection
              value: {{ .Values.proxy.hubConnection }}
            - name: splunkAddress
              value: {{ .Values.proxy.splunkAddress }}
            - name: splunkToken
              value: {{ .Values.proxy.splunkToken }}
            - name: splunkCertThumbprint
              value: {{ .Values.proxy.splunkCertThumbprint }}
