apiVersion: v1
kind: Service
metadata:
  name: proxy 
  namespace: splunk
  labels:
    app: splunk
    role: splunk_proxy
    tier: proxy
spec:
  selector:
    app: splunk
    role: splunk_proxy
    tier: proxy
  ports:
    - name: https
      port: 8000
      targetPort: 8000

